### ISSUE TITLE
Big Size

### ISSUE THREAD

**Issue by ryankarl65** [sullerandras/png_to_xnb#4]
PNG ( 160ko ) to XNB (1.14Mo ) is too big !

**Comment by sullerandras** [comment]
XNB files are NOT compressed by default. If you want compression you need
to download and use the xcompress32.dll. Instructions are in the readme.

**Comment by ryankarl65** [comment]
thanks U!

**Comment by ryankarl65** [comment]
![bugs bugs](https://user-images.githubusercontent.com/20144355/29497705-af0273c8-85e4-11e7-8d7b-32176324f23f.png)

BUGS !! with xcompress32.dll

**Comment by sullerandras** [comment]
Indeed it didn't work on a windows machine 😞 
I recompiled now and tested it on Windows 10, so hopefully it will work for you as well. Here is the release:
https://github.com/sullerandras/png_to_xnb/releases/tag/v1.0

**Comment by ryankarl65** [comment]
Sorry for the silence, Thank you!
